// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLz-VxT-FXh1zm9mE4NQtL5iY4ReLTFZw',
    appId: '1:99466942141:android:8869ed86b8ea41aa9209d4',
    messagingSenderId: '99466942141',
    projectId: 'lunch-radar-5d984',
    storageBucket: 'lunch-radar-5d984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlTAQwGaecjxXddkyxymfqNw3UcQYkNzk',
    appId: '1:99466942141:ios:5f290cce3830bca99209d4',
    messagingSenderId: '99466942141',
    projectId: 'lunch-radar-5d984',
    storageBucket: 'lunch-radar-5d984.firebasestorage.app',
    iosBundleId: 'com.kolan.lunchradar',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsHzBak1T-V-fIj-Yh6E3jaEXFh_0qFY',
    appId: '1:99466942141:web:2a400049c492815b9209d4',
    messagingSenderId: '99466942141',
    projectId: 'lunch-radar-5d984',
    authDomain: 'lunch-radar-5d984.firebaseapp.com',
    storageBucket: 'lunch-radar-5d984.firebasestorage.app',
  );

}